### ISSUE TITLE
opus.h is installed in ${includedir}/opus

### ISSUE THREAD

**Issue by joerg-krause** [xiph/libopusenc#11]
pkgconfig installs `opus.h` in ${includedir}/opus:
https://github.com/xiph/opus/blob/652c4559f593d3aad78bd5c85a216eeae7859429/opus.pc.in#L16

Therefore, the correct include path is:
```c
#include <opus/opus.h>
```
instead of:
https://github.com/xiph/libopusenc/blob/0130afaa7ab6141d4d5dad078748dcddf0d63ce8/include/opusenc.h#L57

**Comment by jmvalin** [comment]
It is that way on purpose. The include path is would be something like /usr/include/opus/ and not just /usr/include/

**Comment by joerg-krause** [comment]
You're absolutely right! Sorry, my bad!
