### ISSUE TITLE
size_t needs including <stddef.h>

### ISSUE THREAD

**Issue by joerg-krause** [xiph/libopusenc#12]
`ope_comments_add_picture_from_memory()` has a `size_t` argument, but does not include `<stddef.h>`:
https://github.com/xiph/libopusenc/blob/0130afaa7ab6141d4d5dad078748dcddf0d63ce8/include/opusenc.h#L252

This breaks building libopusenc with the musl C library, which is very strict about including headers.

**Comment by jmvalin** [comment]
Thanks for reporting the issue. Fixed in master.
