### ISSUE TITLE
ope_encoder_create_callbacks segfaults if comments is NULL

### ISSUE THREAD

**Issue by joerg-krause** [xiph/libopusenc#13]
`ope_encoder_create_callbacks()` segfaults if the `comments` parameter is `NULL`:

```C
int ope_error;
OggOpusEnc* enc = ope_encoder_create_callbacks(&ope_callbacks, this, NULL, 48000, 2, 0, &ope_error);
```

Turned out `ope_comments_create()` needs to be called before:
```C
int ope_error;
OggOpusComments* comments = ope_comments_create();
OggOpusEnc* enc = ope_encoder_create_callbacks(&ope_callbacks, this, comments, 48000, 2, 0, &ope_error);
```

**Comment by jmvalin** [comment]
I'm not sure I understand the issue. You shouldn't pass comments=NULL to ope_encoder_create_callbacks() in the first place.

**Comment by joerg-krause** [comment]
This issue is that a segmentation fault is not a nice way of telling the user of a library he did something wrong or something unexpected. Maybe add a check if `comments` is NULL and return `OPE_BAD_ARG`?

**Comment by joerg-krause** [comment]
No further comment. Closing.
