### ISSUE TITLE
ogg123 unable to play the ogg file created by the example program

### ISSUE THREAD

**Issue by sarath-crypto** [xiph/libopusenc#23]
I am trying to play the ogg file created by example program given in this library. But i am getting error. In input file is S16_LE 16 bit@48000 raw sample , and able to play using "cat pcm.raw| aplay -r 48000 -f S16_LE" successfully.
Error opening o4.ogg using the oggvorbis module.  The file may be corrupted.
Any guidance will help me.
#include <stdio.h>
#include "opusenc.h"

#define READ_SIZE 256

int main(int argc, char **argv) {
  FILE *fin;
  OggOpusEnc *enc;
  OggOpusComments *comments;
  int error;
  fin = fopen("pcm.raw", "rb");
  if (!fin) {
    fprintf(stderr, "cannot open input file: %s\n", argv[1]);
    return 1;
  }
  comments = ope_comments_create();
  ope_comments_add(comments, "ARTIST", "Someone");
  ope_comments_add(comments, "TITLE", "Some track");
  enc = ope_encoder_create_file("o4.ogg", comments, 48000, 1, 0, &error);
  if (!enc) {
    fprintf(stderr, "error encoding to file %s: %s\n", argv[2], ope_strerror(error));
    ope_comments_destroy(comments);
    fclose(fin);
    return 1;
  }
  while (1) {
    short buf[2*READ_SIZE];
    int ret = fread(buf, 2*sizeof(short), READ_SIZE, fin);
    if (ret > 0) {
      ope_encoder_write(enc, buf, ret);
    } else break;
  }
  ope_encoder_drain(enc);
  ope_encoder_destroy(enc);
  ope_comments_destroy(comments);
  fclose(fin);
  return 0;
}

**Comment by Rillke** [comment]
ogg123 is part of [vorbis-tools](https://github.com/xiph/vorbis-tools/tree/master/ogg123). However, this is opus, not  vorbis. Have you tried any other ogg/opus file?  See `man ogg123` for help on supported codecs.

**Comment by sarath-crypto** [comment]
ogg123 will not support opus codec. Any command line recommended player for ubuntu for opus codec ,using ogg/matroska container?

**Comment by rillian** [comment]
There are `opusdec` and `opusinfo` programmes in the `opus-tools` package on Ubuntu. I'd recommend those for verifying your files from the command line. You can also try general media players, like the system app based on GStreamer, or web browsers like Firefox.

**Comment by sarath-crypto** [comment]
ffplay -nodisp pcm.ogg working fine thank you
