### ISSUE TITLE
the out file of opusenc_example is different with run opusenc

### ISSUE THREAD

**Issue by berniezheng** [xiph/libopusenc#26]
I try to use opusenc for converting a pcm to ogg file,  so I modified the sampling rate and the number of channels in the opusenc_example code to the real value of the pcm.  And use the opusenc_example to make convert.

But the duration of this ogg file is half of the output of the tool, and it sounds faster than normal, Can anyone help me？ 

The format of pcm file:
sampling rate: 8000
channels:         1

(1) ----------opusenc_example------------------
```C
#include <stdio.h>
#include "opusenc.h"

#define READ_SIZE 256

int main(int argc, char **argv) {
  FILE *fin;
  OggOpusEnc *enc;
  OggOpusComments *comments;
  int error;
  if (argc != 3) {
    fprintf(stderr, "usage: %s <raw pcm input> <Ogg Opus output>\n", argv[0]);
    return 1;
  }
  fin = fopen(argv[1], "rb");
  if (!fin) {
    fprintf(stderr, "cannot open input file: %s\n", argv[1]);
    return 1;
  }
  comments = ope_comments_create();
  ope_comments_add(comments, "ARTIST", "Someone");
  ope_comments_add(comments, "TITLE", "Some track");
  enc = ope_encoder_create_file(argv[2], comments, **8000, 1, 0**, &error);
  if (!enc) {
    fprintf(stderr, "error encoding to file %s: %s\n", argv[2], ope_strerror(error));
    ope_comments_destroy(comments);
    fclose(fin);
    return 1;
  }
  while (1) {
    short buf[2*READ_SIZE];
    int ret = fread(buf, 2*sizeof(short), READ_SIZE, fin);
    if (ret > 0) {
      ope_encoder_write(enc, buf, ret);
    } else break;
  }
  ope_encoder_drain(enc);
  ope_encoder_destroy(enc);
  ope_comments_destroy(comments);
  fclose(fin);
  return 0;
}
```
**./opusenc_example 8k16bits_1chan.pcm example_out.opus**

(2) opusenc 8k16bits_1chan.pcm tool_out.opus --raw-rate 8000 --raw-chan 1 --raw

![image](https://user-images.githubusercontent.com/88152959/127520926-498bd3a3-7009-4bca-8bc7-2d8e59ffd4a5.png)
![image](https://user-images.githubusercontent.com/88152959/127521017-2ed5524b-5d01-450e-8cde-7046d8d91453.png)

here is the pcm file.
[pcm.zip](https://github.com/xiph/libopusenc/files/6901702/pcm.zip)

**Comment by rillian** [comment]
I didn't try to reproduce, but it looks like you're reading two 2 16-bit integers per sample, but your example filename says it's mono, not stereo. If you ask for 1 encoded channel with `ope_encoder_create_*` I'd expect that to just double to size of your input buffer. But if you ask for stereo and feed in mono data two samples at a time, that would explain the doubled playback speed. So maybe double-check that?

**Comment by berniezheng** [comment]
> I didn't try to reproduce, but it looks like you're reading two 2 16-bit integers per sample, but your example filename says it's mono, not stereo. If you ask for 1 encoded channel with `ope_encoder_create_*` I'd expect that to just double to size of your input buffer. But if you ask for stereo and feed in mono data two samples at a time, that would explain the doubled playback speed. So maybe double-check that?

Thank you rillian, you are right!

![image](https://user-images.githubusercontent.com/88152959/127606079-36d2c970-534e-49fc-b1ff-675506047997.png)

After I made the above modification, the conversion was normal.
