### ISSUE TITLE
libopusenc depends only on libopus？which verson？

### ISSUE THREAD

**Issue by windyer39** [xiph/libopusenc#4]
1，you say “libopusenc depends only on libopus.”but

![image](https://user-images.githubusercontent.com/7529613/32261558-6057db7c-be9d-11e7-9968-bb7c88185fff.png)

2，so，i add  speexdsp source code ， but

![image](https://user-images.githubusercontent.com/7529613/32261562-6c66abb4-be9d-11e7-827e-afe8efbfcc48.png)

3，so，i 。。。

![image](https://user-images.githubusercontent.com/7529613/32261569-715989de-be9d-11e7-911f-77a044dca5ca.png)

but

![Uploading image.png…]()

now，what can i do。i use libopus 1.2 and 1.2beta and 1.1.3 test in android！

**Comment by jmvalin** [comment]
(copy of response on the mailing list)

libopusenc does *not* require speexdsp. It copes some source code from it. The reason it's trying to #include that missing file is because OUTSIDE_SPEEX isn't defined. This is set in Makefile.am, but I assume you're overriding some/all of the build system.
