### ISSUE TITLE
libopusenc calling ambisonics when ENABLE_EXPERIMENTAL_AMBISONICS is not defined

### ISSUE THREAD

**Issue by silverbacknet** [xiph/libopusenc#9]
In libopusenc's opusenc.c line 194, calling ambisonics is guarded by OPUS_HAVE_OPUS_PROJECTION_H, while in opus, they're guarded by ENABLE_EXPERIMENTAL_AMBISONICS. I have opus_projection.h, since I have the most recent commits, but I've intentionally not defined ENABLE_EXPERIMENTAL_AMBISONICS, so I get link errors. Easy enough to work around, but an error nonetheless.

**Comment by jmvalin** [comment]
Normally, when you disable ambisonics support in libopus, the symbols should still exist. They're just supposed to return OPUS_UNIMPLEMENTED when you call them. Are you using master for both libopusenc and libopus?

**Comment by silverbacknet** [comment]
Oops, looks like the actual problem is that opus_projection_encoder.c and _decoder.c aren't included in the VS2015 projects. Once attached and built, all is well.

**Comment by mark4o** [comment]
Thanks, your patch is now available in libopus git master.
